import csv
import pathlib
import subprocess
from typing import Dict, List, Tuple

import gradio as gr
import plotly.graph_objects as go


ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "output"
DEFAULT_EXECUTABLE = ROOT / "build-linux" / "MyProject"
DEFAULT_MODEL = ROOT / "models" / "sample_frame.fea"


NODE_COLS = ["key", "x", "y", "z"]
LINE_COLS = ["key", "node1", "node2"]
SUPPORT_DEF_COLS = ["name", "type"]
SUPPORT_COLS = ["node", "support"]
SECTION_COLS = ["name", "width", "height"]
MATERIAL_COLS = ["name", "E", "G"]
ASSIGN_SECTION_COLS = ["line", "section"]
ASSIGN_MATERIAL_COLS = ["line", "material"]
LOAD_CASE_COLS = ["key", "name"]
NODAL_LOAD_COLS = ["lc", "node", "Fx", "Fy", "Fz", "Mx", "My", "Mz"]
LINE_CONC_COLS = ["lc", "line", "rel", "Fx", "Fy", "Fz", "Mx", "My", "Mz"]
LINE_DIST_COLS = [
    "lc",
    "line",
    "rel_start",
    "rel_end",
    "FxS",
    "FyS",
    "FzS",
    "MxS",
    "MyS",
    "MzS",
    "FxE",
    "FyE",
    "FzE",
    "MxE",
    "MyE",
    "MzE",
]

TEMPLATE_CHOICES = [
    "Sample Portal Frame",
    "Two Story Frame",
    "Cantilever Beam",
    "Simple Triangular Truss",
]


def sample_rows(columns: List[str]) -> List[List[str]]:
    if columns == NODE_COLS:
        return [["1", "0", "0", "0"], ["2", "0", "0", "5"], ["3", "10", "0", "5"], ["4", "10", "0", "0"]]
    if columns == LINE_COLS:
        return [["1", "1", "2"], ["2", "2", "3"], ["3", "3", "4"]]
    if columns == SUPPORT_DEF_COLS:
        return [["FIXED", "FIXED"]]
    if columns == SUPPORT_COLS:
        return [["1", "FIXED"], ["4", "FIXED"]]
    if columns == SECTION_COLS:
        return [["R300x500", "0.30", "0.50"]]
    if columns == MATERIAL_COLS:
        return [["CONCRETE", "2.0e10", "8.0e9"]]
    if columns == ASSIGN_SECTION_COLS:
        return [["1", "R300x500"], ["2", "R300x500"], ["3", "R300x500"]]
    if columns == ASSIGN_MATERIAL_COLS:
        return [["1", "CONCRETE"], ["2", "CONCRETE"], ["3", "CONCRETE"]]
    if columns == LOAD_CASE_COLS:
        return [["1", "DL"], ["2", "LL"]]
    if columns == NODAL_LOAD_COLS:
        return [["1", "2", "-1000", "2000", "-3000", "100", "200", "300"], ["1", "3", "-1000", "2000", "-3000", "100", "200", "300"], ["2", "2", "0", "-4000", "0", "0", "0", "0"], ["2", "3", "0", "-4000", "0", "0", "0", "0"]]
    if columns == LINE_CONC_COLS:
        return [["1", "2", "0.50", "-500", "1000", "1500", "100", "200", "300"]]
    if columns == LINE_DIST_COLS:
        return [["1", "2", "0.25", "0.75", "-1000", "-2000", "3000", "100", "200", "300", "2000", "-3000", "-4000", "200", "300", "400"]]
    return []


def clean_table_rows(rows: List[List[object]], num_cols: int) -> List[List[str]]:
    clean = []
    for row in rows or []:
        if row is None:
            continue
        values = ["" if value is None else str(value).strip() for value in row[:num_cols]]
        if len(values) < num_cols:
            values.extend([""] * (num_cols - len(values)))
        if any(value != "" for value in values):
            clean.append(values)
    return clean


def parse_int(text: str, label: str, errors: List[str]) -> int | None:
    try:
        return int(text)
    except Exception:
        errors.append(f"Invalid integer for {label}: {text}")
        return None


def parse_float(text: str, label: str, errors: List[str]) -> float | None:
    try:
        return float(text)
    except Exception:
        errors.append(f"Invalid number for {label}: {text}")
        return None


def tables_to_model_text(
    nodes,
    lines,
    support_defs,
    supports,
    sections,
    materials,
    assign_sections,
    assign_materials,
    load_cases,
    nodal_loads,
    line_conc_loads,
    line_dist_loads,
) -> str:
    node_rows = clean_table_rows(nodes, len(NODE_COLS))
    line_rows = clean_table_rows(lines, len(LINE_COLS))
    support_def_rows = clean_table_rows(support_defs, len(SUPPORT_DEF_COLS))
    support_rows = clean_table_rows(supports, len(SUPPORT_COLS))
    section_rows = clean_table_rows(sections, len(SECTION_COLS))
    material_rows = clean_table_rows(materials, len(MATERIAL_COLS))
    assign_section_rows = clean_table_rows(assign_sections, len(ASSIGN_SECTION_COLS))
    assign_material_rows = clean_table_rows(assign_materials, len(ASSIGN_MATERIAL_COLS))
    load_case_rows = clean_table_rows(load_cases, len(LOAD_CASE_COLS))
    nodal_rows = clean_table_rows(nodal_loads, len(NODAL_LOAD_COLS))
    conc_rows = clean_table_rows(line_conc_loads, len(LINE_CONC_COLS))
    dist_rows = clean_table_rows(line_dist_loads, len(LINE_DIST_COLS))

    out = [
        "# Generated by dashboard Model Builder",
        "# NODE key x y z",
        "# LINE key node1 node2",
        "# SUPPORT_DEF name FIXED|PINNED|ROLLER",
        "# SUPPORT node supportName",
        "# SECTION_RECT name width height",
        "# MATERIAL name E G",
        "# ASSIGN_SECTION line sectionName",
        "# ASSIGN_MATERIAL line materialName",
        "# LOAD_CASE key name",
        "# NODAL_LOAD lc node Fx Fy Fz Mx My Mz",
        "# LINE_CONC_LOAD lc line rel Fx Fy Fz Mx My Mz",
        "# LINE_DIST_LOAD lc line rel_start rel_end FxS FyS FzS MxS MyS MzS FxE FyE FzE MxE MyE MzE",
        "",
    ]

    for row in node_rows:
        out.append(f"NODE {row[0]} {row[1]} {row[2]} {row[3]}")
    out.append("")

    for row in line_rows:
        out.append(f"LINE {row[0]} {row[1]} {row[2]}")
    out.append("")

    for row in support_def_rows:
        out.append(f"SUPPORT_DEF {row[0]} {row[1].upper()}")
    for row in support_rows:
        out.append(f"SUPPORT {row[0]} {row[1]}")
    out.append("")

    for row in section_rows:
        out.append(f"SECTION_RECT {row[0]} {row[1]} {row[2]}")
    for row in material_rows:
        out.append(f"MATERIAL {row[0]} {row[1]} {row[2]}")
    for row in assign_section_rows:
        out.append(f"ASSIGN_SECTION {row[0]} {row[1]}")
    for row in assign_material_rows:
        out.append(f"ASSIGN_MATERIAL {row[0]} {row[1]}")
    out.append("")

    for row in load_case_rows:
        out.append(f"LOAD_CASE {row[0]} {row[1]}")
    out.append("")

    for row in nodal_rows:
        out.append(f"NODAL_LOAD {row[0]} {row[1]} {row[2]} {row[3]} {row[4]} {row[5]} {row[6]} {row[7]}")
    for row in conc_rows:
        out.append(f"LINE_CONC_LOAD {row[0]} {row[1]} {row[2]} {row[3]} {row[4]} {row[5]} {row[6]} {row[7]} {row[8]}")
    for row in dist_rows:
        out.append(
            "LINE_DIST_LOAD " + " ".join(row)
        )

    return "\n".join(out).rstrip() + "\n"


def validate_tables(
    nodes,
    lines,
    support_defs,
    supports,
    sections,
    materials,
    assign_sections,
    assign_materials,
    load_cases,
    nodal_loads,
    line_conc_loads,
    line_dist_loads,
) -> str:
    errors: List[str] = []
    warnings: List[str] = []

    node_rows = clean_table_rows(nodes, len(NODE_COLS))
    line_rows = clean_table_rows(lines, len(LINE_COLS))
    support_def_rows = clean_table_rows(support_defs, len(SUPPORT_DEF_COLS))
    support_rows = clean_table_rows(supports, len(SUPPORT_COLS))
    section_rows = clean_table_rows(sections, len(SECTION_COLS))
    material_rows = clean_table_rows(materials, len(MATERIAL_COLS))
    assign_section_rows = clean_table_rows(assign_sections, len(ASSIGN_SECTION_COLS))
    assign_material_rows = clean_table_rows(assign_materials, len(ASSIGN_MATERIAL_COLS))
    load_case_rows = clean_table_rows(load_cases, len(LOAD_CASE_COLS))
    nodal_rows = clean_table_rows(nodal_loads, len(NODAL_LOAD_COLS))
    conc_rows = clean_table_rows(line_conc_loads, len(LINE_CONC_COLS))
    dist_rows = clean_table_rows(line_dist_loads, len(LINE_DIST_COLS))

    node_ids = set()
    for row in node_rows:
        node_id = parse_int(row[0], "NODE key", errors)
        if node_id is not None:
            if node_id in node_ids:
                errors.append(f"Duplicate NODE key: {node_id}")
            node_ids.add(node_id)
        parse_float(row[1], f"NODE {row[0]} x", errors)
        parse_float(row[2], f"NODE {row[0]} y", errors)
        parse_float(row[3], f"NODE {row[0]} z", errors)

    line_ids = set()
    for row in line_rows:
        line_id = parse_int(row[0], "LINE key", errors)
        n1 = parse_int(row[1], f"LINE {row[0]} node1", errors)
        n2 = parse_int(row[2], f"LINE {row[0]} node2", errors)
        if line_id is not None:
            if line_id in line_ids:
                errors.append(f"Duplicate LINE key: {line_id}")
            line_ids.add(line_id)
        if n1 is not None and n1 not in node_ids:
            errors.append(f"LINE {row[0]} references missing NODE {n1}")
        if n2 is not None and n2 not in node_ids:
            errors.append(f"LINE {row[0]} references missing NODE {n2}")

    support_def_names = set()
    for row in support_def_rows:
        name = row[0]
        support_type = row[1].upper()
        if not name:
            errors.append("SUPPORT_DEF has empty name")
        if name in support_def_names:
            errors.append(f"Duplicate SUPPORT_DEF name: {name}")
        support_def_names.add(name)
        if support_type not in {"FIXED", "PINNED", "ROLLER"}:
            errors.append(f"SUPPORT_DEF {name} has invalid type {support_type}")

    for row in support_rows:
        node = parse_int(row[0], "SUPPORT node", errors)
        support_name = row[1]
        if node is not None and node not in node_ids:
            errors.append(f"SUPPORT references missing NODE {node}")
        if support_name not in support_def_names:
            errors.append(f"SUPPORT references missing SUPPORT_DEF {support_name}")

    section_names = set()
    for row in section_rows:
        if not row[0]:
            errors.append("SECTION_RECT has empty name")
        if row[0] in section_names:
            errors.append(f"Duplicate SECTION_RECT name: {row[0]}")
        section_names.add(row[0])
        parse_float(row[1], f"SECTION_RECT {row[0]} width", errors)
        parse_float(row[2], f"SECTION_RECT {row[0]} height", errors)

    material_names = set()
    for row in material_rows:
        if not row[0]:
            errors.append("MATERIAL has empty name")
        if row[0] in material_names:
            errors.append(f"Duplicate MATERIAL name: {row[0]}")
        material_names.add(row[0])
        parse_float(row[1], f"MATERIAL {row[0]} E", errors)
        parse_float(row[2], f"MATERIAL {row[0]} G", errors)

    for row in assign_section_rows:
        line = parse_int(row[0], "ASSIGN_SECTION line", errors)
        section = row[1]
        if line is not None and line not in line_ids:
            errors.append(f"ASSIGN_SECTION references missing LINE {line}")
        if section not in section_names:
            errors.append(f"ASSIGN_SECTION references missing SECTION_RECT {section}")

    for row in assign_material_rows:
        line = parse_int(row[0], "ASSIGN_MATERIAL line", errors)
        material = row[1]
        if line is not None and line not in line_ids:
            errors.append(f"ASSIGN_MATERIAL references missing LINE {line}")
        if material not in material_names:
            errors.append(f"ASSIGN_MATERIAL references missing MATERIAL {material}")

    lc_ids = set()
    for row in load_case_rows:
        lc = parse_int(row[0], "LOAD_CASE key", errors)
        if lc is not None:
            if lc in lc_ids:
                errors.append(f"Duplicate LOAD_CASE key: {lc}")
            lc_ids.add(lc)
        if not row[1]:
            errors.append(f"LOAD_CASE {row[0]} has empty name")

    def validate_lc_line_node(row: List[str], source: str, lc_idx: int, line_idx: int | None = None, node_idx: int | None = None):
        lc = parse_int(row[lc_idx], f"{source} lc", errors)
        if lc is not None and lc not in lc_ids:
            errors.append(f"{source} references missing LOAD_CASE {lc}")
        if line_idx is not None:
            line = parse_int(row[line_idx], f"{source} line", errors)
            if line is not None and line not in line_ids:
                errors.append(f"{source} references missing LINE {line}")
        if node_idx is not None:
            node = parse_int(row[node_idx], f"{source} node", errors)
            if node is not None and node not in node_ids:
                errors.append(f"{source} references missing NODE {node}")

    for row in nodal_rows:
        validate_lc_line_node(row, "NODAL_LOAD", 0, node_idx=1)
        for idx, label in enumerate(["Fx", "Fy", "Fz", "Mx", "My", "Mz"], start=2):
            parse_float(row[idx], f"NODAL_LOAD {label}", errors)

    for row in conc_rows:
        validate_lc_line_node(row, "LINE_CONC_LOAD", 0, line_idx=1)
        for idx, label in enumerate(["rel", "Fx", "Fy", "Fz", "Mx", "My", "Mz"], start=2):
            parse_float(row[idx], f"LINE_CONC_LOAD {label}", errors)

    for row in dist_rows:
        validate_lc_line_node(row, "LINE_DIST_LOAD", 0, line_idx=1)
        for idx, label in enumerate(LINE_DIST_COLS[2:], start=2):
            parse_float(row[idx], f"LINE_DIST_LOAD {label}", errors)

    if not support_rows:
        warnings.append("No supports defined (model may be unstable).")
    if not load_case_rows:
        warnings.append("No load cases defined.")
    if not (nodal_rows or conc_rows or dist_rows):
        warnings.append("No loads defined.")

    if errors:
        return "❌ Validation failed\n\n" + "\n".join(f"- {error}" for error in errors)

    message = "✅ Validation passed"
    if warnings:
        message += "\n\nWarnings:\n" + "\n".join(f"- {warning}" for warning in warnings)
    return message


def save_model_file(model_path: str, model_text: str) -> str:
    target = pathlib.Path(model_path).expanduser().resolve()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(model_text, encoding="utf-8")
    return f"Saved model to: {target}"


def parse_fea_model(model_path: str):
    path = pathlib.Path(model_path).expanduser().resolve()
    if not path.exists():
        raise gr.Error(f"Model file not found: {path}")

    nodes = []
    lines = []
    support_defs = []
    supports = []
    sections = []
    materials = []
    assign_sections = []
    assign_materials = []
    load_cases = []
    nodal_loads = []
    line_conc_loads = []
    line_dist_loads = []

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        tokens = line.split()
        kind = tokens[0]
        payload = tokens[1:]

        if kind == "NODE" and len(payload) == 4:
            nodes.append(payload)
        elif kind == "LINE" and len(payload) == 3:
            lines.append(payload)
        elif kind == "SUPPORT_DEF" and len(payload) == 2:
            support_defs.append(payload)
        elif kind == "SUPPORT" and len(payload) == 2:
            supports.append(payload)
        elif kind == "SECTION_RECT" and len(payload) == 3:
            sections.append(payload)
        elif kind == "MATERIAL" and len(payload) == 3:
            materials.append(payload)
        elif kind == "ASSIGN_SECTION" and len(payload) == 2:
            assign_sections.append(payload)
        elif kind == "ASSIGN_MATERIAL" and len(payload) == 2:
            assign_materials.append(payload)
        elif kind == "LOAD_CASE" and len(payload) >= 2:
            load_cases.append([payload[0], payload[1]])
        elif kind == "NODAL_LOAD" and len(payload) == 8:
            nodal_loads.append(payload)
        elif kind == "LINE_CONC_LOAD" and len(payload) == 9:
            line_conc_loads.append(payload)
        elif kind == "LINE_DIST_LOAD" and len(payload) == 16:
            line_dist_loads.append(payload)

    model_text = tables_to_model_text(
        nodes,
        lines,
        support_defs,
        supports,
        sections,
        materials,
        assign_sections,
        assign_materials,
        load_cases,
        nodal_loads,
        line_conc_loads,
        line_dist_loads,
    )

    return (
        nodes,
        lines,
        support_defs,
        supports,
        sections,
        materials,
        assign_sections,
        assign_materials,
        load_cases,
        nodal_loads,
        line_conc_loads,
        line_dist_loads,
        model_text,
        f"Loaded model: {path}",
    )


def template_tables(template_name: str):
    if template_name == "Two Story Frame":
        return (
            [["1", "0", "0", "0"], ["2", "0", "0", "4"], ["3", "0", "0", "8"], ["4", "6", "0", "8"], ["5", "6", "0", "4"], ["6", "6", "0", "0"]],
            [["1", "1", "2"], ["2", "2", "3"], ["3", "3", "4"], ["4", "4", "5"], ["5", "5", "6"]],
            [["FIXED", "FIXED"]],
            [["1", "FIXED"], ["6", "FIXED"]],
            [["SEC", "0.30", "0.40"]],
            [["STEEL", "2.10e11", "8.00e10"]],
            [["1", "SEC"], ["2", "SEC"], ["3", "SEC"], ["4", "SEC"], ["5", "SEC"]],
            [["1", "STEEL"], ["2", "STEEL"], ["3", "STEEL"], ["4", "STEEL"], ["5", "STEEL"]],
            [["1", "DEAD"], ["2", "LIVE"], ["3", "WIND"]],
            [["3", "3", "3000", "0", "0", "0", "0", "0"], ["3", "4", "3000", "0", "0", "0", "0", "0"]],
            [],
            [["1", "3", "0.0", "1.0", "0", "-2000", "0", "0", "0", "0", "0", "-2000", "0", "0", "0", "0"], ["2", "3", "0.0", "1.0", "0", "-1000", "0", "0", "0", "0", "0", "-1000", "0", "0", "0", "0"]],
        )

    if template_name == "Cantilever Beam":
        return (
            [["1", "0", "0", "0"], ["2", "5", "0", "0"]],
            [["1", "1", "2"]],
            [["FIXED", "FIXED"]],
            [["1", "FIXED"]],
            [["SEC", "0.20", "0.30"]],
            [["STEEL", "2.10e11", "8.00e10"]],
            [["1", "SEC"]],
            [["1", "STEEL"]],
            [["1", "POINT"]],
            [["1", "2", "0", "-5000", "0", "0", "0", "0"]],
            [],
            [],
        )

    if template_name == "Simple Triangular Truss":
        return (
            [["1", "0", "0", "0"], ["2", "4", "0", "0"], ["3", "2", "3", "0"]],
            [["1", "1", "2"], ["2", "2", "3"], ["3", "1", "3"]],
            [["PIN", "PINNED"], ["ROL", "ROLLER"]],
            [["1", "PIN"], ["2", "ROL"]],
            [["TRUSS", "0.10", "0.10"]],
            [["STEEL", "2.00e11", "7.70e10"]],
            [["1", "TRUSS"], ["2", "TRUSS"], ["3", "TRUSS"]],
            [["1", "STEEL"], ["2", "STEEL"], ["3", "STEEL"]],
            [["1", "SERVICE"]],
            [["1", "3", "0", "-8000", "0", "0", "0", "0"]],
            [],
            [],
        )

    return (
        sample_rows(NODE_COLS),
        sample_rows(LINE_COLS),
        sample_rows(SUPPORT_DEF_COLS),
        sample_rows(SUPPORT_COLS),
        sample_rows(SECTION_COLS),
        sample_rows(MATERIAL_COLS),
        sample_rows(ASSIGN_SECTION_COLS),
        sample_rows(ASSIGN_MATERIAL_COLS),
        sample_rows(LOAD_CASE_COLS),
        sample_rows(NODAL_LOAD_COLS),
        sample_rows(LINE_CONC_COLS),
        sample_rows(LINE_DIST_COLS),
    )


def apply_template(template_name: str):
    tables = template_tables(template_name)
    model_text = tables_to_model_text(*tables)
    status = f"Template applied: {template_name}"
    return (*tables, model_text, status)


def reset_builder_tables():
    tables = template_tables("Sample Portal Frame")
    return (*tables, tables_to_model_text(*tables), "Builder reset to sample template.")


def build_and_validate_text(
    nodes,
    lines,
    support_defs,
    supports,
    sections,
    materials,
    assign_sections,
    assign_materials,
    load_cases,
    nodal_loads,
    line_conc_loads,
    line_dist_loads,
):
    model_text = tables_to_model_text(
        nodes,
        lines,
        support_defs,
        supports,
        sections,
        materials,
        assign_sections,
        assign_materials,
        load_cases,
        nodal_loads,
        line_conc_loads,
        line_dist_loads,
    )
    validation = validate_tables(
        nodes,
        lines,
        support_defs,
        supports,
        sections,
        materials,
        assign_sections,
        assign_materials,
        load_cases,
        nodal_loads,
        line_conc_loads,
        line_dist_loads,
    )
    return model_text, validation


def run_solver_from_builder(
    executable_path,
    model_path,
    output_dir,
    model_text,
):
    save_msg = save_model_file(model_path, model_text)
    solver_msg = run_solver(executable_path, model_path, output_dir)
    return f"{save_msg}\n\n{solver_msg}"


def read_csv(path: pathlib.Path) -> List[Dict[str, str]]:
    with open(path, newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def list_load_cases(output_dir: pathlib.Path) -> List[int]:
    ids = []
    for file in output_dir.glob("deflections_lc*.csv"):
        name = file.stem
        suffix = name.replace("deflections_lc", "")
        if suffix.isdigit():
            ids.append(int(suffix))
    return sorted(ids)


def build_figure(output_dir: pathlib.Path, load_case_id: int, scale: float) -> go.Figure:
    nodes = read_csv(output_dir / "nodes.csv")
    lines = read_csv(output_dir / "lines.csv")
    defs = read_csv(output_dir / f"deflections_lc{load_case_id}.csv")

    node_map = {int(node["id"]): node for node in nodes}
    def_map = {int(row["id"]): row for row in defs}

    fig = go.Figure()

    for line in lines:
        node1 = node_map[int(line["node1"])]
        node2 = node_map[int(line["node2"])]

        x = [float(node1["x"]), float(node2["x"])]
        y = [float(node1["y"]), float(node2["y"])]
        z = [float(node1["z"]), float(node2["z"])]

        fig.add_trace(
            go.Scatter3d(
                x=x,
                y=y,
                z=z,
                mode="lines",
                name="Original",
                line={"color": "#1f77b4", "width": 6},
                showlegend=False,
            )
        )

        def1 = def_map[int(line["node1"])]
        def2 = def_map[int(line["node2"])]

        xd = [
            float(node1["x"]) + scale * float(def1["ux"]),
            float(node2["x"]) + scale * float(def2["ux"]),
        ]
        yd = [
            float(node1["y"]) + scale * float(def1["uy"]),
            float(node2["y"]) + scale * float(def2["uy"]),
        ]
        zd = [
            float(node1["z"]) + scale * float(def1["uz"]),
            float(node2["z"]) + scale * float(def2["uz"]),
        ]

        fig.add_trace(
            go.Scatter3d(
                x=xd,
                y=yd,
                z=zd,
                mode="lines",
                name="Deflected",
                line={"color": "#f2c744", "width": 7},
                showlegend=False,
            )
        )

    fig.update_layout(
        title=f"FEA Result - Load Case {load_case_id}",
        scene={
            "xaxis_title": "X",
            "yaxis_title": "Y",
            "zaxis_title": "Z",
            "aspectmode": "data",
        },
        margin={"l": 0, "r": 0, "t": 40, "b": 0},
    )
    return fig


def solver_status_text(exit_code: int, stdout: str, stderr: str) -> str:
    text = [f"Solver exit code: {exit_code}"]
    if stdout.strip():
        text.append("\nSTDOUT:\n" + stdout.strip())
    if stderr.strip():
        text.append("\nSTDERR:\n" + stderr.strip())
    return "\n".join(text)


def run_solver(executable_path: str, model_path: str, output_dir: str) -> str:
    executable = pathlib.Path(executable_path).expanduser().resolve()
    if not executable.exists():
        return f"Executable not found: {executable}"

    model = pathlib.Path(model_path).expanduser().resolve()
    if not model.exists():
        return f"Model file not found: {model}"

    out = pathlib.Path(output_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)

    process = subprocess.run(
        [str(executable), "--model", str(model), "--output", str(out)],
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        check=False,
    )
    return solver_status_text(process.returncode, process.stdout, process.stderr)


def refresh_load_cases(output_dir: str) -> Tuple[gr.Dropdown, str]:
    out = pathlib.Path(output_dir).expanduser().resolve()
    if not out.exists():
        return gr.Dropdown(choices=[], value=None), f"Output directory not found: {out}"

    cases = list_load_cases(out)
    if not cases:
        return gr.Dropdown(choices=[], value=None), "No deflection files found. Run the solver first."

    return gr.Dropdown(choices=cases, value=cases[0]), f"Found load cases: {cases}"


def choose_file(path: str) -> str:
    if not path:
        return ""
    return str(pathlib.Path(path).expanduser().resolve())


def choose_output_from_any(path: str) -> str:
    if not path:
        return str(DEFAULT_OUTPUT)
    candidate = pathlib.Path(path).expanduser().resolve()
    if candidate.is_dir():
        return str(candidate)
    return str(candidate.parent)


def render(output_dir: str, load_case_id: int, scale: float):
    out = pathlib.Path(output_dir).expanduser().resolve()
    if not out.exists():
        raise gr.Error(f"Output directory not found: {out}")
    if load_case_id is None:
        raise gr.Error("Please refresh and select a load case.")

    required = [
        out / "nodes.csv",
        out / "lines.csv",
        out / f"deflections_lc{load_case_id}.csv",
    ]
    for file in required:
        if not file.exists():
            raise gr.Error(f"Missing file: {file}")

    fig = build_figure(out, load_case_id, scale)
    return fig


def build_app() -> gr.Blocks:
    with gr.Blocks(title="FEA Solver Dashboard") as demo:
        gr.Markdown("# FEA Solver Dashboard")
        gr.Markdown("Educational FEA workflow: build model -> validate -> solve -> visualize.")

        with gr.Row():
            executable_path = gr.Textbox(label="Solver executable", value=str(DEFAULT_EXECUTABLE))
            model_path = gr.Textbox(label="Model file (.fea)", value=str(DEFAULT_MODEL))
            output_dir = gr.Textbox(label="Output directory", value=str(DEFAULT_OUTPUT))

        with gr.Tabs():
            with gr.Tab("Model Builder"):
                with gr.Accordion("Browse paths", open=False):
                    with gr.Row():
                        exec_picker = gr.FileExplorer(label="Pick solver executable", root_dir=str(ROOT), glob="**/*", file_count="single")
                        model_picker = gr.FileExplorer(label="Pick model file", root_dir=str(ROOT), glob="**/*.fea", file_count="single")
                        output_picker = gr.FileExplorer(label="Pick output folder/file", root_dir=str(ROOT), glob="**/*", file_count="single")

                with gr.Row():
                    template_name = gr.Dropdown(label="Template", choices=TEMPLATE_CHOICES, value="Sample Portal Frame")
                    apply_template_btn = gr.Button("Apply template")

                with gr.Row():
                    load_model_btn = gr.Button("Load model file")
                    reset_btn = gr.Button("Reset sample")
                    validate_btn = gr.Button("Validate")
                    build_text_btn = gr.Button("Build model text")
                    save_btn = gr.Button("Save model")
                    solve_btn = gr.Button("Save + Solve")

                builder_status = gr.Textbox(label="Builder status", lines=8)

                with gr.Accordion("Geometry", open=True):
                    nodes_df = gr.Dataframe(headers=NODE_COLS, value=sample_rows(NODE_COLS), row_count=(8, "dynamic"), column_count=(len(NODE_COLS), "fixed"), type="array", label="Nodes")
                    lines_df = gr.Dataframe(headers=LINE_COLS, value=sample_rows(LINE_COLS), row_count=(8, "dynamic"), column_count=(len(LINE_COLS), "fixed"), type="array", label="Lines")

                with gr.Accordion("Supports / Properties", open=False):
                    support_def_df = gr.Dataframe(headers=SUPPORT_DEF_COLS, value=sample_rows(SUPPORT_DEF_COLS), row_count=(6, "dynamic"), column_count=(len(SUPPORT_DEF_COLS), "fixed"), type="array", label="Support Definitions")
                    support_df = gr.Dataframe(headers=SUPPORT_COLS, value=sample_rows(SUPPORT_COLS), row_count=(8, "dynamic"), column_count=(len(SUPPORT_COLS), "fixed"), type="array", label="Support Assignment")
                    section_df = gr.Dataframe(headers=SECTION_COLS, value=sample_rows(SECTION_COLS), row_count=(6, "dynamic"), column_count=(len(SECTION_COLS), "fixed"), type="array", label="Sections (Rectangular)")
                    material_df = gr.Dataframe(headers=MATERIAL_COLS, value=sample_rows(MATERIAL_COLS), row_count=(6, "dynamic"), column_count=(len(MATERIAL_COLS), "fixed"), type="array", label="Materials")
                    assign_section_df = gr.Dataframe(headers=ASSIGN_SECTION_COLS, value=sample_rows(ASSIGN_SECTION_COLS), row_count=(8, "dynamic"), column_count=(len(ASSIGN_SECTION_COLS), "fixed"), type="array", label="Assign Sections")
                    assign_material_df = gr.Dataframe(headers=ASSIGN_MATERIAL_COLS, value=sample_rows(ASSIGN_MATERIAL_COLS), row_count=(8, "dynamic"), column_count=(len(ASSIGN_MATERIAL_COLS), "fixed"), type="array", label="Assign Materials")

                with gr.Accordion("Load Cases / Loads", open=False):
                    load_case_df = gr.Dataframe(headers=LOAD_CASE_COLS, value=sample_rows(LOAD_CASE_COLS), row_count=(8, "dynamic"), column_count=(len(LOAD_CASE_COLS), "fixed"), type="array", label="Load Cases")
                    nodal_load_df = gr.Dataframe(headers=NODAL_LOAD_COLS, value=sample_rows(NODAL_LOAD_COLS), row_count=(12, "dynamic"), column_count=(len(NODAL_LOAD_COLS), "fixed"), type="array", label="Nodal Loads")
                    line_conc_df = gr.Dataframe(headers=LINE_CONC_COLS, value=sample_rows(LINE_CONC_COLS), row_count=(8, "dynamic"), column_count=(len(LINE_CONC_COLS), "fixed"), type="array", label="Line Concentrated Loads")
                    line_dist_df = gr.Dataframe(headers=LINE_DIST_COLS, value=sample_rows(LINE_DIST_COLS), row_count=(8, "dynamic"), column_count=(len(LINE_DIST_COLS), "fixed"), type="array", label="Line Distributed Loads")

                model_text = gr.Textbox(
                    label="Generated .fea model",
                    lines=20,
                    value=tables_to_model_text(*template_tables("Sample Portal Frame")),
                )

            with gr.Tab("Solve & Visualize"):
                with gr.Row():
                    run_button = gr.Button("Run solver")
                    refresh_button = gr.Button("Refresh load cases")

                solver_log = gr.Textbox(label="Solver log", lines=10)

                with gr.Row():
                    load_case = gr.Dropdown(label="Load case", choices=[], value=None)
                    scale = gr.Slider(label="Deflection scale", minimum=1.0, maximum=10000.0, value=1000.0, step=1.0)

                plot_button = gr.Button("Render")
                plot = gr.Plot(label="3D Structure")

        all_builder_inputs = [
            nodes_df,
            lines_df,
            support_def_df,
            support_df,
            section_df,
            material_df,
            assign_section_df,
            assign_material_df,
            load_case_df,
            nodal_load_df,
            line_conc_df,
            line_dist_df,
        ]

        exec_picker.change(fn=choose_file, inputs=[exec_picker], outputs=[executable_path])
        model_picker.change(fn=choose_file, inputs=[model_picker], outputs=[model_path])
        output_picker.change(fn=choose_output_from_any, inputs=[output_picker], outputs=[output_dir])

        load_model_btn.click(
            fn=parse_fea_model,
            inputs=[model_path],
            outputs=all_builder_inputs + [model_text, builder_status],
        )

        reset_btn.click(
            fn=reset_builder_tables,
            inputs=[],
            outputs=all_builder_inputs + [model_text, builder_status],
        )

        apply_template_btn.click(
            fn=apply_template,
            inputs=[template_name],
            outputs=all_builder_inputs + [model_text, builder_status],
        )

        build_text_btn.click(
            fn=build_and_validate_text,
            inputs=all_builder_inputs,
            outputs=[model_text, builder_status],
        )

        validate_btn.click(
            fn=validate_tables,
            inputs=all_builder_inputs,
            outputs=[builder_status],
        )

        save_btn.click(
            fn=lambda mpath, mtext: save_model_file(mpath, mtext),
            inputs=[model_path, model_text],
            outputs=[builder_status],
        )

        solve_btn.click(
            fn=run_solver_from_builder,
            inputs=[executable_path, model_path, output_dir, model_text],
            outputs=[solver_log],
        )

        run_button.click(fn=run_solver, inputs=[executable_path, model_path, output_dir], outputs=[solver_log])
        refresh_button.click(fn=refresh_load_cases, inputs=[output_dir], outputs=[load_case, solver_log])
        plot_button.click(fn=render, inputs=[output_dir, load_case, scale], outputs=[plot])

    return demo


if __name__ == "__main__":
    app = build_app()
    app.launch(server_name="127.0.0.1", server_port=7860, inbrowser=True)
